name: cursach_reports_backend
version: 1.0.0
description: An ORM starter application for Angel3 framework
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  # angel3_auth: ^4.0.0
  angel3_configuration: ^6.0.0
  angel3_cors: ^6.0.1
  angel3_framework: ^6.0.0
  angel3_jael: ^6.0.1
  angel3_migration: ^6.0.0
  angel3_orm: ^6.0.0
  angel3_orm_postgres: ^6.0.0
  angel3_serialize: ^6.0.0
  angel3_production: ^6.0.0
  angel3_static: ^6.0.0
  angel3_validate: ^6.0.0
  belatuk_pretty_logging: ^4.0.0
  optional: ^6.0.0
  logging: ^1.0.0
  crypto: ^3.0.2
  

dev_dependencies:
  angel3_hot: ^6.0.0
  angel3_migration_runner: ^6.0.1
  angel3_orm_generator: ^6.0.0
  angel3_serialize_generator: ^6.0.0
  angel3_test: ^6.0.0
  build_runner: ^2.0.3
  io: ^1.0.3
  test: ^1.17.5
  lints: ^1.0.0
  build_web_compilers:



