# Development-only server configuration.
debug: true
host: 127.0.0.1
port: 3000
postgres:
  host: localhost
  port: 5432
  database_name: habrdb
  username: habrpguser
  password: pgpwd4habr
  useSSL: false
  time_zone: UTC
jwt_secret: "6ZXjiUn06SzvsucByYDeE4Oj0YYlXjFx"